inherit_gem:
  scc-codestyle:
    - default.yml

inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.5
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - .bundle/**/*
    - db/schema.rb
    - db/migrate/20180420145408_init_schema.rb
    - features/**/*
    - vendor/**/*
    - tmp/**/*
    - lib/locale/*
    - package/**/*


Style/TrailingUnderscoreVariable:
  Enabled: false

RSpec/ExampleLength:
  Exclude:
    - spec/lib/rmt/cli/mirror_spec.rb

RSpec/ExpectOutput:
  Exclude:
    - spec/lib/rmt/cli/mirror_spec.rb

RSpec/MultipleExpectations:
  Exclude:
    - spec/lib/rmt/cli/mirror_spec.rb

Metrics/ClassLength:
  Exclude:
    - lib/rmt/downloader.rb
  Max: 250

Naming/FileName:
  Exclude:
    - Dangerfile

Rails/Output:
  Exclude:
    - lib/rmt/cli/**/*

Naming/MethodParameterName:
  AllowedNames:
  - to
  - id

RSpec/NestedGroups:
  Max: 4

Style/FormatStringToken:
  EnforcedStyle: template
  Exclude:
    - lib/rmt/cli/mirror.rb

Style/OpenStructUse:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

# We disable this check since we are stubing class methods
# that are already tested in their respective tests.
# This way we circumvent tight coupling between tests and
# implementation.
# Count: 107 offenses
RSpec/SubjectStub:
  Enabled: false

Layout/LineLength:
  Exclude:
    - config/initializers/new_framework_defaults_7_0.rb
    - engines/instance_verification/spec/requests/api/connect/v3/systems/products_controller_spec.rb
