inherit_gem:
  scc-codestyle:
    - default.yml

inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 3.4
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - .bundle/**/*
    - db/schema.rb
    - db/migrate/20180420145408_init_schema.rb
    - features/**/*
    - vendor/**/*
    - tmp/**/*
    - lib/locale/*
    - package/**/*


Naming/PredicatePrefix:
  Enabled: true

RSpec/ExampleLength:
  Exclude:
    - spec/lib/rmt/cli/mirror_spec.rb

RSpec/ExpectOutput:
  Exclude:
    - spec/lib/rmt/cli/mirror_spec.rb

RSpec/MultipleExpectations:
  Exclude:
    - spec/lib/rmt/cli/mirror_spec.rb

Metrics/ClassLength:
  Exclude:
    - lib/rmt/downloader.rb
  Max: 250

Naming/FileName:
  Exclude:
    - Dangerfile

Rails/Output:
  Exclude:
    - lib/rmt/cli/**/*

Naming/MethodParameterName:
  AllowedNames:
  - to
  - id

RSpec/NestedGroups:
  Max: 4

Style/FormatStringToken:
  EnforcedStyle: template
  Exclude:
    - lib/rmt/cli/mirror.rb

Style/OpenStructUse:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

# We disable this check since we are stubing class methods
# that are already tested in their respective tests.
# This way we circumvent tight coupling between tests and
# implementation.
# Count: 107 offenses
RSpec/SubjectStub:
  Enabled: false

FactoryBot/SyntaxMethods:
  Enabled: false

FactoryBot/ConsistentParenthesesStyle:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpecRails/HaveHttpStatus:
  Enabled: false

Rails/HttpStatus:
  Enabled: false

RSpecRails/InferredSpecType:
  Enabled: false

Style/RedundantConstantBase:
  Enabled: false

RSpec/MatchArray:
  Enabled: false

RSpec/BeNil:
  Enabled: false

RSpec/ClassCheck:
  Enabled: false

RSpec/VerifiedDoubleReference:
  Enabled: false

RSpec/ExampleWording:
  Enabled: false

RSpec/ReceiveMessages:
  Enabled: false  

Style/RedundantParentheses:
  Enabled: false

Style/FileNull:
  Enabled: false

Rails/StripHeredoc:
  Enabled: false

Performance/StringIdentifierArgument:
  Enabled: false

Layout/HeredocIndentation:
  Enabled: false

FactoryBot/FactoryAssociationWithStrategy:
  Enabled: false

Rails/DurationArithmetic:
  Enabled: false

FactoryBot/AssociationStyle:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/ReturnNilInPredicateMethodDefinition:
  Enabled: false

Rails/FindEach:
  Enabled: false

RSpec/RemoveConst:
  Enabled: false

RSpec/NoExpectationExample:
  Enabled: false

Style/RedundantStringEscape:
  Enabled: false

Style/RedundantFormat:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

Rails/RedundantActiveRecordAllMethod:
  Enabled: false

Rails/ThreeStateBooleanColumn:
  Enabled: false

Rails/SelectMap:
  Enabled: false

Rails/RootPathnameMethods:
  Enabled: false

Performance/MapMethodChain:
  Enabled: false

Style/SafeNavigationChainLength:
  Enabled: false