inherit_gem:
  scc-codestyle:
    - default.yml

inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.5
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - .bundle/**/*
    - db/schema.rb
    - db/migrate/20180420145408_init_schema.rb
    - features/**/*
    - vendor/**/*
    - tmp/**/*
    - lib/locale/*
    - package/**/*


Style/TrailingUnderscoreVariable:
  Enabled: false

Naming/FileName:
  Exclude:
    - Dangerfile

Rails/Output:
  Exclude:
    - lib/rmt/cli/**/*

Naming/MethodParameterName:
  AllowedNames:
  - to
  - id

RSpec/NestedGroups:
  Max: 4

Style/FormatStringToken:
  EnforcedStyle: template

Style/OpenStructUse:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false
