d /var/lib/rmt 0750 _rmt nginx -
d /var/lib/rmt/regsharing 0750 _rmt nginx -
d /var/lib/rmt/tmp 0750 _rmt nginx -
d /var/lib/rmt/public 0755 _rmt nginx -
d /var/lib/rmt/public/repo 0755 _rmt nginx -
d /var/lib/rmt/public/suma 0755 _rmt nginx -
