require 'fileutils'

class RMT::FileUtils

  ##
  # This method tries to deduplicate a file if it was already downloaded elsewhere.
  #
  # Params:
  # - +checksum_type+:: The type of checksum (MD5, SHA256, ...).
  # - +checksum+:: The checksum hex generated by a checksum algorithm.
  # - +destination+:: The path where to place the deduplicated file.
  #
  # Returns:
  # - True if deduplicated, false if not.
  def self.deduplicate(checksum_type, checksum_value, destination)
    local_path = DownloadedFile.get_local_path_by_checksum(checksum_type, checksum_value)
    return false unless local_path

    if RMT::Config.deduplication_by_hardlink?
      ::FileUtils.ln(local_path, destination)
    else
      ::FileUtils.cp(local_path, destination)
    end

    true
  end

end
