---
# RMT role variables (not meant to be overridden)

rmt_packages:
  - rmt-server-3
  - mariadb
  - nginx

rmt_public_dir: /var/lib/rmt/public
rmt_config_path: /etc/rmt.conf
rmt_nginx_vhost_dir: /etc/nginx/vhosts.d

rmt_systemd_dir: /etc/systemd/system
