# This playbook installs rmt but does not populate it
# To do so, ssh into the host and run the appropriate "rmt-cli" commands for
# mirroring products.

- name: Add RMT repo
  zypper_repository:
    repo: "{{ rmt_repo_url }}"
    name: "{{ rmt_repo_name }}"
    auto_import_keys: yes

# Configure rmt
- name: Modify rmt.conf
  template:
    src: rmt.conf.j2
    dest: /etc/rmt.conf
    mode: 0644
    owner: root
    group: root
  notify: Restart rmt

- name: Provision HTTP (Plain Text) nginx config
  template:
    src: rmt_host_plain_text.conf.j2
    dest: /etc/nginx/vhosts.d/rmt-server-http.conf
    mode: 0644
    owner: root
    group: root
  notify: Reload nginx

- name: Provision RMT Upstream section
  template:
    src: rmt_upstreams.conf
    dest: /etc/nginx/vhosts.d/rmt_upstreams.conf
    mode: 0644
    owner: root
    group: root
  notify: Reload nginx

- name: Create SSL directory
  file:
    path: /etc/rmt/ssl
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Generate RMT server private key
  community.crypto.openssl_privatekey:
    path: /etc/rmt/ssl/rmt-server.key
    size: 4096
    mode: 0600
    owner: root
    group: root

- name: Generate RMT server certificate
  community.crypto.x509_certificate:
    path: /etc/rmt/ssl/rmt-server.crt
    privatekey_path: /etc/rmt/ssl/rmt-server.key
    provider: selfsigned
    selfsigned_not_after: "+3650d"
    mode: 0644
    owner: root
    group: root

- name: Generate RMT CA private key
  community.crypto.openssl_privatekey:
    path: /etc/rmt/ssl/rmt-ca.key
    size: 4096
    mode: 0600
    owner: root
    group: root

- name: Generate RMT CA certificate
  community.crypto.x509_certificate:
    path: /etc/rmt/ssl/rmt-ca.crt
    privatekey_path: /etc/rmt/ssl/rmt-ca.key
    provider: selfsigned
    selfsigned_not_after: "+3650d"
    mode: 0644
    owner: root
    group: root

- name: Provision HTTPS (SSL) nginx config
  template:
    src: rmt_host_http_ssl.conf.j2
    dest: /etc/nginx/vhosts.d/rmt-server-https.conf
    mode: 0644
    owner: root
    group: root
  notify: Reload nginx

- name: Install rmt & dependencies
  zypper:
    name:
      - rmt-server
      - mariadb
      - nginx
    state: latest

- name: Ensure PyMySQL is installed for Python 3.11
  ansible.builtin.pip:
    name: PyMySQL
    executable: /usr/bin/pip3.11
# Uncomment this when creating fresh setup with empty database
#- name: Create a new database with name 'rmt'
  #community.mysql.mysql_db:
    #name: rmt
    #state: present

#- name: Create database user 'rmt'
  #community.mysql.mysql_user:
    #name: rmt
    #password: rmt
    #priv: 'rmt.*:ALL'
    #state: present
  #no_log: true
