---
# Synopsis: Creates a custom Ubuntu docker image using Docker Build for SUSE Repository Management Tool.
#
# Comments:
#   - Meant to be uploaded to a Docker registry such as AWS ECR.

##################################
# Ansible role related variables #
##################################

# The AWS region that the AWS ECR registry resides in and the region that will be used for S3 backups.
aws_region: 'REDACTED'

# Whether to have the role become root when running the Docker commands on the target host.
docker_container_become: true

# The name of the Docker registry to log into and pull the Docker image from.
docker_registry_name: ''

# The 'registry/name' of the Docker image to pull for the containers. For example: 'gitlab/gitlab-ee:latest'
docker_image: "{{ docker_registry_name }}/test-suse-rmt:latest"

###############################
# Container related variables #
###############################

# Whether to create a Docker container using either of the two methods: Docker CLI or Docker Compose.
docker_create_container: false

# Whether to use Docker Compose to create the container.
docker_compose: true

# The name to use for the container once it is created.
container_name: 'suse-rmt'

# The container restart policy. Valid options are 'no' (The default if nothing is specified), 'always', 'on-failure', and 'unless-stopped'.
container_restart_policy: 'always'


#################
# Vault Secrets #
#################

# The address of the Vault server to pull secrets from (Include https:// in the value).
vault_address: 'https://vault.core.sapns2.us'

# A list of secrets to pull from Vault. See the 'README.md' of the 'vault-auth' role for details.
vault_secrets:
  - secret_path: 'kv_secrets/dev/infrastructure/repositories/suse_rmt_docker_image_secrets'
    secret_version: 'latest'
    secret_key: 'mysql_host'
    ansible_fact_name: 'mysql_host'
  - secret_path: 'kv_secrets/dev/infrastructure/repositories/suse_rmt_docker_image_secrets'
    secret_version: 'latest'
    secret_key: 'mysql_database'
    ansible_fact_name: 'mysql_database'
  - secret_path: 'kv_secrets/dev/infrastructure/repositories/suse_rmt_docker_image_secrets'
    secret_version: 'latest'
    secret_key: 'mysql_root_password'
    ansible_fact_name: 'mysql_root_password'
  - secret_path: 'kv_secrets/dev/infrastructure/repositories/suse_rmt_docker_image_secrets'
    secret_version: 'latest'
    secret_key: 'mysql_user'
    ansible_fact_name: 'mysql_user'
  - secret_path: 'kv_secrets/dev/infrastructure/repositories/suse_rmt_docker_image_secrets'
    secret_version: 'latest'
    secret_key: 'mysql_password'
    ansible_fact_name: 'mysql_password'
  - secret_path: 'kv_secrets/dev/infrastructure/repositories/suse_rmt_docker_image_secrets'
    secret_version: 'latest'
    secret_key: 'scc_username'
    ansible_fact_name: 'scc_username'
  - secret_path: 'kv_secrets/dev/infrastructure/repositories/suse_rmt_docker_image_secrets'
    secret_version: 'latest'
    secret_key: 'scc_password'
    ansible_fact_name: 'scc_password'
  - secret_path: 'kv_secrets/dev/infrastructure/repositories/suse_rmt_docker_image_secrets'
    secret_version: 'latest'
    secret_key: 'secret_key_base'
    ansible_fact_name: 'secret_key_base'

##########################################
# SUSE Customer Center related variables #
##########################################

# Allow for syncing from RMT docker container to SUSE Customer Center 
scc_sync_systems: true

##################################
# Docker build related variables #
##################################

# Whether to use Docker Build to create a Docker image from a dockerfile.
docker_build_image: false

# The name of the dockerfile within the 'templates/' directory to use when building a Docker image (For example, 'concourse-ubuntu/dockerfile.j2').
docker_build_template_filename: 'suse-rmt/dockerfile.j2'

# Whether to push the Docker image to the registry after it is built via Docker Build.
docker_build_push: true

# The name of the Docker image to build from (For example, 'ubuntu:18.04').
docker_build_from_image: 'opensuse/leap:15.1'

# The SUSE RMT and mysql containers template file
docker_compose_template_filename: 'templates/suse-rmt/docker-compose.yml.j2'

# Directory path used to store the docker-compose.yml file
docker_compose_directory: '/usr/local/docker-compose'

...
