pipeline {
  agent {
    label 'scc-happy-customer'
  }

  stages {
    stage('checkout') {
      steps {
        script {
          currentBuild.displayName = "#${BUILD_NUMBER}: ${branch}"
        }

        git url: 'git@github.com:SUSE/rmt.git', branch: "${branch}"
      }
    }
    stage('copy configuration') {
      steps {
        sh 'cp /home/jenkins/options-local-connect-prophet.yml integration/prophet/options-local.yml'
      }
    }
    stage('run prophet') {
      steps {
        sh 'ruby ./integration/prophet/prophet.rb'
      }
    }
  }
}
